version: 2

references:

working_directory: &working_directory
  ~/terraform

terraform_image: &terraform_image
  hashicorp/terraform:light

yamllint_image: &yamllint_image
  sdesbure/yamllint:latest

ansiblelint_image: &ansiblelint_image
  yokogawa/ansible-lint:latest

ansible_image: &ansible_image
  williamyeh/ansible:debian9

terraform_config: &terraform_config
  docker:
    - image: *terraform_image
  working_directory: *working_directory
  environment:
    BASH_ENV: /root/.bashrc

yamllint_config: &yamllint_config
  docker:
    - image: *yamllint_image
  working_directory: *working_directory

ansiblelint_config: &ansiblelint_config
  docker:
    - image: *ansiblelint_image
  working_directory: *working_directory

ansible_config: &ansible_config
  docker:
    - image: *ansible_image
  working_directory: *working_directory

repo_cache_key: &repo_cache_key
  v1-repo-{{ .Branch }}-{{ .Revision }}

# Step to restore repository from cache
restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

set_terraform_environment: &set_terraform_environment
  run:
    name: set terraform environment
    command: |
      cd && touch $BASH_ENV
      echo 'export TERRAFORM_ENVIRONMENT=prod' >> $BASH_ENV
      echo 'export TERRAFORM_DIR=./terraform' >> $BASH_ENV

      #if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #  echo 'export TERRAFORM_ENVIRONMENT=prod' >> $BASH_ENV
      #else
      #  echo 'export TERRAFORM_ENVIRONMENT=dev' >> $BASH_ENV
      #fi

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      source $BASH_ENV
      terraform init $TERRAFORM_DIR
      terraform workspace select $TERRAFORM_ENVIRONMENT $TERRAFORM_DIR

tfnotify_install: &tfnotify_install
  run:
    name: tfnotify install
    command: |
      curl -vOL https://github.com/mercari/tfnotify/releases/download/v0.2.0/tfnotify_v0.2.0_linux_amd64.tar.gz
      tar -xzvf tfnotify_v0.2.0_linux_amd64.tar.gz
      mv tfnotify_v0.2.0_linux_amd64/tfnotify /usr/local/bin
      rm -rf tfnotify_v0.2.0_linux_amd64*

terraform_apply_job: &terraform_apply_job
  <<: *terraform_config
  steps:
    - *restore_repo
    - *set_terraform_environment
    - *terraform_init
    - attach_workspace:
        at: *working_directory
    - run:
        name: terraform apply
        command: |
          source $BASH_ENV
          terraform apply --auto-approve terraform.plan
jobs:
  yaml-lint:
    <<: *yamllint_config
    steps:
      - checkout
      - run:
          name: yaml-lint
          command: cd ansible; find . -name "*.y*ml" | xargs -r yamllint

  ansible-lint:
    <<: *ansiblelint_config
    steps:
      - checkout
      - run:
          name: ansible-lint
          command: cd ansible; find . -name "*.y*ml" | xargs -r ansible-lint --force-color

  ansible-check:
    <<: *ansible_config
    steps:
      - *restore_repo
      - run:
          name: ansible check
          command: cd ansible; ansible-playbook playbook.yaml --syntax-check

  terraform-lint:
    <<: *terraform_config
    steps:
      - checkout
      - *set_terraform_environment
      - run:
          name: terraform lint
          command: |
            source $BASH_ENV
            if [ $(terraform fmt $TERRAFORM_DIR | grep -v .terraform | tee fmt_result.txt | wc -l) -gt 0 ]; then
              echo "Terraform files require syntax reformating:"
              echo
              cat fmt_result.txt
              rm fmt_result.txt
              git checkout -- .
              echo
              echo "Please run terraform fmt"
              exit 1
            fi
      - *save_repo

  terraform-plan:
    <<: *terraform_config
    steps:
      - *restore_repo
      - *set_terraform_environment
      - *terraform_init
      - *tfnotify_install
      - run:
          name: terraform plan
          command: |
            source $BASH_ENV
            terraform plan -out=terraform.plan $TERRAFORM_DIR
      - run:
          name: tfnotify plan
          command: terraform plan terraform.plan | tfnotify plan

      - persist_to_workspace:
          root: *working_directory
          paths:
            - terraform.plan

  terraform-apply:
    <<: *terraform_apply_job
  #terraform-apply-with-approval:
  #  <<: *terraform_apply_job

workflows:
  version: 2
  lint_plan_apply:
    jobs:
      - yaml-lint
      - ansible-lint
      - ansible-check
      - terraform-lint
      - terraform-plan:
          requires:
            - terraform-lint
      #- approve:
      #    type: approval
      #    requires:
      #      - terraform-plan
      #    filters:
      #      branches:
      #        only: master
      #- apply-with-approval:
      #    requires:
      #      - approve
      #    filters:
      #      branches:
      #        only: master
      - terraform-apply:
          requires:
            - terraform-plan
          filters:
            branches:
              only: master
